import '../models/models.dart';

/// Everything collected by the "Refer a customer" / "New requirement" flow.
class EnquiryDraft {
  EnquiryDraft({
    this.existingCustomerId,
    this.customerName = '',
    this.customerPhone = '',
    this.customerEmail,
    this.city = '',
    this.area = '',
    this.pincode,
    this.address,
    this.categoryId,
    this.productId,
    this.brandId,
    this.requirement = '',
    Map<String, String>? answers,
    this.contactPreference = ContactPreference.callAnytime,
    this.preferredTime,
    this.otpVerified = false,
    this.potentialValue,
  }) : answers = answers ?? {};

  String? existingCustomerId;
  String customerName;
  String customerPhone;
  String? customerEmail;
  String city;
  String area;
  String? pincode;
  String? address;
  String? categoryId;
  String? productId;
  String? brandId;
  String requirement;
  Map<String, String> answers;
  ContactPreference contactPreference;
  String? preferredTime;
  bool otpVerified;
  double? potentialValue;
}

/// Quotation form contents, used for new quotations, drafts and revisions.
class QuotationDraft {
  QuotationDraft({
    required this.enquiryId,
    required this.vendorId,
    List<QuotationItem>? items,
    this.discount = 0,
    this.taxPercent = 18,
    this.installation = 0,
    this.delivery = 0,
    this.validityDays = 15,
    this.terms = '',
    this.timelineDays = 7,
    this.notes = '',
    List<String>? attachments,
  })  : items = items ?? [],
        attachments = attachments ?? [];

  factory QuotationDraft.fromQuotation(Quotation q) => QuotationDraft(
        enquiryId: q.enquiryId,
        vendorId: q.vendorId,
        items: [...q.items],
        discount: q.discount,
        taxPercent: q.taxPercent,
        installation: q.installation,
        delivery: q.delivery,
        validityDays: q.validityDays,
        terms: q.terms,
        timelineDays: q.timelineDays,
        notes: q.notes,
        attachments: [...q.attachments],
      );

  final String enquiryId;
  final String vendorId;
  List<QuotationItem> items;
  double discount;
  double taxPercent;
  double installation;
  double delivery;
  int validityDays;
  String terms;
  int timelineDays;
  String notes;
  List<String> attachments;

  double get subtotal => items.fold(0, (s, i) => s + i.total);
  double get taxable => subtotal - discount + installation + delivery;
  double get taxAmount => taxable * taxPercent / 100;
  double get total => taxable + taxAmount;
}

/// Data collected by the public sign-up flow.
class SignUpData {
  SignUpData({
    this.role = UserRole.sales,
    this.name = '',
    this.phone = '',
    this.email,
    this.city = '',
    this.area = '',
    this.pincode,
    this.companyName,
    this.address,
    this.gstin,
    List<String>? categoryIds,
    List<String>? brandIds,
    List<String>? serviceCities,
    this.loginId = '',
    this.password = '',
    this.acceptedTerms = false,
  })  : categoryIds = categoryIds ?? [],
        brandIds = brandIds ?? [],
        serviceCities = serviceCities ?? [];

  UserRole role;
  String name;
  String phone;
  String? email;
  String city;
  String area;
  String? pincode;
  String? companyName;
  String? address;
  String? gstin;
  List<String> categoryIds;
  List<String> brandIds;
  List<String> serviceCities;
  String loginId;
  String password;
  bool acceptedTerms;
}

/// Admin "create user" form contents.
class NewUserData {
  NewUserData({
    this.role = UserRole.sales,
    this.name = '',
    this.phone = '',
    this.email,
    this.city = '',
    this.area,
    this.franchiseId,
    this.salesType = SalesType.company,
    this.companyName,
    List<String>? categoryIds,
  }) : categoryIds = categoryIds ?? [];

  UserRole role;
  String name;
  String phone;
  String? email;
  String city;
  String? area;
  String? franchiseId;
  SalesType salesType;
  String? companyName;
  List<String> categoryIds;
}

/// Credentials generated by admin, shown once so they can be handed over.
class GeneratedLogin {
  const GeneratedLogin({
    required this.userId,
    required this.loginId,
    required this.password,
  });

  final String userId;
  final String loginId;
  final String password;
}
