import 'enums.dart';
import 'json.dart';

class FollowUp {
  const FollowUp({
    required this.id,
    this.enquiryId,
    required this.type,
    required this.assignedUserId,
    required this.dueAt,
    this.notes = '',
    this.done = false,
    this.doneAt,
    this.outcome,
    required this.createdAt,
  });

  final String id;
  final String? enquiryId;
  final FollowUpType type;
  final String assignedUserId;
  final DateTime dueAt;
  final String notes;
  final bool done;
  final DateTime? doneAt;
  final String? outcome;
  final DateTime createdAt;

  FollowUp copyWith({
    DateTime? dueAt,
    String? notes,
    bool? done,
    DateTime? doneAt,
    String? outcome,
  }) =>
      FollowUp(
        id: id,
        enquiryId: enquiryId,
        type: type,
        assignedUserId: assignedUserId,
        dueAt: dueAt ?? this.dueAt,
        notes: notes ?? this.notes,
        done: done ?? this.done,
        doneAt: doneAt ?? this.doneAt,
        outcome: outcome ?? this.outcome,
        createdAt: createdAt,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'enquiryId': enquiryId,
        'type': type.name,
        'assignedUserId': assignedUserId,
        'dueAt': dueAt.toIso8601String(),
        'notes': notes,
        'done': done,
        'doneAt': doneAt?.toIso8601String(),
        'outcome': outcome,
        'createdAt': createdAt.toIso8601String(),
      };

  factory FollowUp.fromJson(Map<String, dynamic> j) => FollowUp(
        id: j['id'] as String,
        enquiryId: j['enquiryId'] as String?,
        type: enumByName(FollowUpType.values, j['type'], FollowUpType.customerCall),
        assignedUserId: j['assignedUserId'] as String,
        dueAt: DateTime.parse(j['dueAt'] as String),
        notes: j['notes'] as String? ?? '',
        done: j['done'] as bool? ?? false,
        doneAt: parseDate(j['doneAt']),
        outcome: j['outcome'] as String?,
        createdAt: DateTime.parse(j['createdAt'] as String),
      );
}

/// Work generated by the system (verify, review quotation…) or added by hand.
class TaskItem {
  const TaskItem({
    required this.id,
    required this.kind,
    this.enquiryId,
    this.refId,
    this.title,
    required this.assignedUserId,
    required this.dueAt,
    this.done = false,
    this.doneAt,
    required this.createdAt,
  });

  final String id;
  final TaskKind kind;
  final String? enquiryId;

  /// Related record, e.g. a quotation or vendor ID.
  final String? refId;

  /// Only used for [TaskKind.general]; other kinds build their title from [kind].
  final String? title;
  final String assignedUserId;
  final DateTime dueAt;
  final bool done;
  final DateTime? doneAt;
  final DateTime createdAt;

  TaskItem copyWith({bool? done, DateTime? doneAt, DateTime? dueAt}) => TaskItem(
        id: id,
        kind: kind,
        enquiryId: enquiryId,
        refId: refId,
        title: title,
        assignedUserId: assignedUserId,
        dueAt: dueAt ?? this.dueAt,
        done: done ?? this.done,
        doneAt: doneAt ?? this.doneAt,
        createdAt: createdAt,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'kind': kind.name,
        'enquiryId': enquiryId,
        'refId': refId,
        'title': title,
        'assignedUserId': assignedUserId,
        'dueAt': dueAt.toIso8601String(),
        'done': done,
        'doneAt': doneAt?.toIso8601String(),
        'createdAt': createdAt.toIso8601String(),
      };

  factory TaskItem.fromJson(Map<String, dynamic> j) => TaskItem(
        id: j['id'] as String,
        kind: enumByName(TaskKind.values, j['kind'], TaskKind.general),
        enquiryId: j['enquiryId'] as String?,
        refId: j['refId'] as String?,
        title: j['title'] as String?,
        assignedUserId: j['assignedUserId'] as String,
        dueAt: DateTime.parse(j['dueAt'] as String),
        done: j['done'] as bool? ?? false,
        doneAt: parseDate(j['doneAt']),
        createdAt: DateTime.parse(j['createdAt'] as String),
      );
}

/// An in-app notification. Text is built from [event] and [params] at display
/// time so it follows the reader's language.
class AppNotification {
  const AppNotification({
    required this.id,
    required this.userId,
    required this.event,
    this.enquiryId,
    this.params = const {},
    required this.createdAt,
    this.read = false,
    this.route,
  });

  final String id;
  final String userId;
  final NotificationEvent event;
  final String? enquiryId;
  final Map<String, String> params;
  final DateTime createdAt;
  final bool read;

  /// Where tapping the notification should go for this recipient.
  final String? route;

  AppNotification copyWith({bool? read}) => AppNotification(
        id: id,
        userId: userId,
        event: event,
        enquiryId: enquiryId,
        params: params,
        createdAt: createdAt,
        read: read ?? this.read,
        route: route,
      );

  Map<String, dynamic> toJson() => {
        'id': id,
        'userId': userId,
        'event': event.name,
        'enquiryId': enquiryId,
        'params': params,
        'createdAt': createdAt.toIso8601String(),
        'read': read,
        'route': route,
      };

  factory AppNotification.fromJson(Map<String, dynamic> j) => AppNotification(
        id: j['id'] as String,
        userId: j['userId'] as String,
        event: enumByName(
            NotificationEvent.values, j['event'], NotificationEvent.configChanged),
        enquiryId: j['enquiryId'] as String?,
        params: stringMap(j['params']),
        createdAt: DateTime.parse(j['createdAt'] as String),
        read: j['read'] as bool? ?? false,
        route: j['route'] as String?,
      );
}

/// One significant action, kept forever for traceability.
class AuditEntry {
  const AuditEntry({
    required this.id,
    required this.at,
    this.userId,
    this.role,
    required this.action,
    required this.entityType,
    required this.entityId,
    this.enquiryId,
    this.field,
    this.oldValue,
    this.newValue,
    this.note,
  });

  final String id;
  final DateTime at;

  /// Null when the system acted on its own.
  final String? userId;
  final UserRole? role;
  final AuditAction action;

  /// e.g. `enquiry`, `quotation`, `config`, `user`.
  final String entityType;
  final String entityId;
  final String? enquiryId;
  final String? field;
  final String? oldValue;
  final String? newValue;
  final String? note;

  Map<String, dynamic> toJson() => {
        'id': id,
        'at': at.toIso8601String(),
        'userId': userId,
        'role': role?.name,
        'action': action.name,
        'entityType': entityType,
        'entityId': entityId,
        'enquiryId': enquiryId,
        'field': field,
        'oldValue': oldValue,
        'newValue': newValue,
        'note': note,
      };

  factory AuditEntry.fromJson(Map<String, dynamic> j) => AuditEntry(
        id: j['id'] as String,
        at: DateTime.parse(j['at'] as String),
        userId: j['userId'] as String?,
        role: enumByNameOrNull(UserRole.values, j['role']),
        action: enumByName(AuditAction.values, j['action'], AuditAction.edited),
        entityType: j['entityType'] as String,
        entityId: j['entityId'] as String,
        enquiryId: j['enquiryId'] as String?,
        field: j['field'] as String?,
        oldValue: j['oldValue'] as String?,
        newValue: j['newValue'] as String?,
        note: j['note'] as String?,
      );
}

class ConsentRecord {
  const ConsentRecord({
    required this.id,
    required this.userId,
    required this.action,
    required this.policyVersion,
    required this.at,
    this.enquiryId,
  });

  final String id;
  final String userId;
  final ConsentAction action;
  final String policyVersion;
  final DateTime at;
  final String? enquiryId;

  Map<String, dynamic> toJson() => {
        'id': id,
        'userId': userId,
        'action': action.name,
        'policyVersion': policyVersion,
        'at': at.toIso8601String(),
        'enquiryId': enquiryId,
      };

  factory ConsentRecord.fromJson(Map<String, dynamic> j) => ConsentRecord(
        id: j['id'] as String,
        userId: j['userId'] as String,
        action: enumByName(ConsentAction.values, j['action'], ConsentAction.terms),
        policyVersion: j['policyVersion'] as String? ?? 'v1',
        at: DateTime.parse(j['at'] as String),
        enquiryId: j['enquiryId'] as String?,
      );
}
